//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kafe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database2019Entities : DbContext
    {
        public Database2019Entities()
            : base("name=Database2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<Distributor> Distributor { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<UserView> UserView { get; set; }
    }
}
