//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int Id { get; set; }
        public Nullable<int> menu { get; set; }
        public Nullable<int> material { get; set; }
        public Nullable<int> material_consume { get; set; }
    
        public virtual Material Material1 { get; set; }
        public virtual Menu Menu1 { get; set; }
    }
}
